name: Auto Build Dist

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'tsconfig.json'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'tsconfig.json'

permissions:
  contents: write

jobs:
  auto-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24.x'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-v1
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          # Use --legacy-peer-deps to avoid CI errors caused by peer deps / platform bindings
          npm install --legacy-peer-deps --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Auto-commit dist
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' # ⬅️ Commituj tylko na push do master, nie w PR
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Auto-build Bot"

          git add dist/

          if git diff --staged --quiet; then
            echo "Brak zmian w dist"
          else
            git commit -m "🚀 Auto-build dist [skip ci]"
            # Push using the token provided by actions/checkout
            git push origin HEAD:master
            echo "Dist zaktualizowany!"
          fi
