name: SLSA Node.js builder
on:
  release:
    types: [created]
permissions:
  contents: read
jobs:
  build:
    permissions:
      id-token: write # For signing
      contents: read # For repo checkout
      actions: read # For getting workflow run info
    if: startsWith(github.ref, 'refs/tags/')
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@v2.0.0
    with:
      run-scripts: "ci, build"
      node-version: "24"
