name: Generate and Deploy TypeDoc to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write    # potrzebne do pushowania commita
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project (if present)
        run: npm run build --if-present

      - name: Ensure docs directory exists
        run: mkdir -p docs

      - name: Generate TypeDoc
        run: |
          if npm run | grep -q "docs"; then
            npm run docs --if-present
          else
            npx typedoc --options typedoc.json --out docs
          fi

      - name: Show docs contents (debug)
        run: ls -la docs || true

      - name: Commit and push generated docs (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          # jeśli nie ma zmian, wyjdź bez błędu
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update generated docs [skip ci]"
            git push origin HEAD:${{ github.ref_name }}
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # zmień tę ścieżkę jeśli chcesz publikować inny folder (np. './public' lub './dist')
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
